# Site settings
title: Luke O'Hara
email: luke.c.ohara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Windsor based Web developer, a collection of my projects, learnings and wisdom which I would like to impart on the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luke-c-ohara.github.io" # the base hostname & protocol for your site
twitter_username: luke_c_ohara
github_username:  luke-c-ohara

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00b0ff
  secondary: 00b0ff  
  secondary-dark: 00b0ff

# Team names, titles and social links
people:
- name: Luke O'Hara
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: http://twitter.com/luke_c_ohara
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/luke_c_ohara
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/luke-c-ohara

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
