# Site settings
title: Luke O'Hara
email: luke.c.ohara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Windsor based Web developer, a collection of my projects, learnings and wisdom which I would like to impart on the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luke-c-ohara.github.io" # the base hostname & protocol for your site
twitter_username: luke_c_ohara
github_username:  luke-c-ohara

# Build settings
markdown: kramdown
